<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MedicalRadioButton</name>
   <tag></tag>
   <elementGuidId>788ba0c8-d375-4cbd-8f52-9f34185319f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@value=&quot;med&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;filters-container&quot;]/div/div/div[4]/div/label[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
