<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RemoveItemOnCheckoutPage</name>
   <tag></tag>
   <elementGuidId>b60efd61-eef9-4281-8cd0-0fd94694ef67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;top-scroll-container&quot;]/div/div[1]/div[4]/div/div[2]/div[1]/div[4]/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
